-- 0002's grants gave app_user select/insert/update only, matching plain
-- Postgres' real defaults for a freshly created role (nothing, unless
-- asked for) rather than Supabase's implicit "authenticated gets ALL".
-- That left invitations_all's and categories_write's "for all" policies
-- with an unreachable DELETE branch: the privilege check runs before RLS
-- and already says no (42501), so the policy's own using/with check never
-- gets a chance to matter.
--
-- Ruling, consistent with the schema's own "deactivate, don't delete"
-- pattern (see 0001's comments on lots.created_by/movements.created_by):
-- only these two tables are ever actually deletable.
-- - invitations: cancelling a pending invite (doc 04) is a delete, not a
--   status flip - there is no "cancelled" state column to set instead.
-- - categories: a free-text label whose every reference is
--   "on delete set null" (see products.category_id in 0001), so removing
--   one orphans nothing and breaks no audit trail.
--
-- Left closed on purpose: products and suppliers are soft-deleted
-- (active = false), events keep their traceability once movements exist
-- against them, and lots/movements/profiles/businesses were never
-- deletable in the first place - see their own policy comments in 0002.
grant delete on invitations, categories to app_user;
